### ISSUE TITLE
PROD : "No data available for current Filter selection" even though data are avalaible

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1163]
When I try to display a dimension containing many nominal values as color, I get the message "No data available for current Filter selection " even though data exists for the selection chosen. I have to select the filters one by one to display a chart.

**To Reproduce**
1. Go to 'https://www.visualize.admin.ch/de/v/uwrjknXAunVd"
2. Copy and edit this visualisation
3. Edit "Colors" axis
4. Select "Sites"
5. See the message "No data available for current Filter selection "
6. Edit the filter (Colors-Axis) and unselect all (Select none)
7. Select one Site, for exemple "Chamoson", and apply Filters.
8. The chart is displayed.

**Expected behavior**
All sites should be displayed after step 4.

![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/5244bef0-9dfc-4f46-87d0-41b455ccac45)

**Environment (please complete the following information):**

- Visualize environment and version: PROD v3.20.2
- Browser : Edge

**Additional context**

**Comment by bprusinowski** [comment]
Hi @ortnever, thanks for reporting the bug. I checked and it seems that the behavior is correct on TEST (https://test.visualize.admin.ch/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd0066/12). I am not sure at which point the issue was fixed, but it should be fine once we deploy to PROD.

Let me know if the TEST version works according to expectations 👀 If so, I'll close the issue.

**Comment by ortnever** [comment]
Hi @bprusinowski , Yes it's fine on TEST. Thank you for your input. I didn't remember that we already fixed this issue.

**Comment by bprusinowski** [comment]
Sure, no problem! I'm glad it works as expected on TEST 👌
