### ISSUE TITLE
Bars In Barplot Become Transparent When There Is Many

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1315]
When creating a barplot with many entries such as choosing the measurment dates as the x-axis for [bathing water quality](https://int.visualize.admin.ch/de/v/g4SZzytUiLsw) the bars will become transparent and the different colours even harder to distinguish. 

![Transparent_bar_bug](https://github.com/visualize-admin/visualization-tool/assets/111350367/b0bd875a-785d-4808-a340-663d6c752d42)

If this interatction is intentional, then navigating the legend attached to the graphic is rather clunky.

**To Reproduce**

1. Follow the provided link [bathing water quality](https://int.visualize.admin.ch/de/v/g4SZzytUiLsw) or open the [cube]()
2. Choose **barplot** as graphic, **date** as x-axis and **bathing site** for the segmentation

**Expected behavior**
That the colours displayed in the barplot correspond to the ones in the legend

**Comment by bprusinowski** [comment]
Hi @tboeni, thank you for reporting the issue!

Generally, charts with so many items in the legend should be avoided anyway, as even if the bars were wider than in the example, the same colors would still be attached to different values (e.g. purple for `Strandbad Rorschach, Bodensee`, `Ristorante Lido Capolago`, `Ostello della Gioventu`...), misleading the user that they belong to the same category when looking at the chart (we try to advice the user with `For best results, do not select more than 7 values in the visualization` message displayed in the filter panel). Here the bars appear to be transparent due to a very high number of them – you can see in the screenshot below that they're just very, very narrow (but colored correctly).

<img width="435" alt="Screenshot 2024-01-29 at 09 37 29" src="https://github.com/visualize-admin/visualization-tool/assets/52032047/b7b012cf-29b6-4c5a-884a-58dc755d961b">

If we increased the width of the bars, or constrained them to let's say 2px minimum, we would introduce overlaps or make the chart go outside of its viewport. We would need to introduce some kind of a horizontal scrolling behavior which in turn would make the comparisons across X axis harder.

I hope this answer makes sense! I think the issue with the colors not corresponding with the legend could be closed or renamed to something along the lines of "optimize presence of charts with many elements" to better describe the actual problem. What do you think @tboeni, do you see some other way to improve the situation?

cc @KerstinFaye @sosiology
