### ISSUE TITLE
Show more data cube metadata

### ISSUE THREAD

**Issue by herrstucki** [visualize-admin/visualization-tool#135]
- contact email (cf. https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/304)
- link to landingpage (for methodology)

**Comment by PDumasBAR** [comment]
Yes

**Comment by PDumasBAR** [comment]
The link to the cube on opendata,swiss is still not visible.
It should be visible, as a link under the Cube (Dataset) title : 
![image](https://user-images.githubusercontent.com/35593772/167396630-f416a71f-c39d-4359-9d33-613ee3e23793.png)

In the creation process, but especially in the published graphic, because this link allows the user to find much more information about the cube than we can display in the graphic.

The link to opendata.swiss can be build with:
- The base URL : https://opendata.swiss/
- The "perma" keyword
- The cube identifier (<http://purl.org/dc/terms/identifier>) and the publisher identifier (end of <http://purl.org/dc/terms/creator>) separated by @

Samples:
- [Staatsrechnungen - Kategorie](https://opendata.swiss/de/perma/StateAccounts_Category@schweizerisches-bundesarchiv-bar)
- [Stapfer-Enquête: Schule in der Schweiz 1799 (RDF)](https://opendata.swiss/de/perma/stapfer-enquete-1799@schweizerisches-bundesarchiv-bar)

**Comment by l00mi** [comment]
The cube which gets also deployed on opendata.swiss have this annotated, similar to how it is annotated to be shown on visualize. See https://github.com/zazuko/cube-creator/wiki/LINDAS-Specifics#needed-attributes-that-a-cube-shows-up-on-opendataswiss for the details.
