### ISSUE TITLE
Rewrite DataCubeComponents query to use CONSTRUCT instead of SELECT

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1370]
Currently, Visualize fires a lot of `SELECT` queries to fetch dimension metadata (e.g. name, description, scales, available values).

We would like to change this to use more performant `CONSTRUCT` queries, combining several separate queries into one, bigger `CONSTRUCT` query (or more, if complexities arise – but still reducing the overall number of requests to LINDAS).

The current implementation fires SPARQL queries sequentially: Values per Dimension 1,2,3... n, and finally fetches the hierarchies - much of which can happen concurrently (as it's already the case i.e. for multiple hierarchies) ... after the cube shape is loaded initially.

Switching to `CONSTRUCT` paradigm should result in increased performance.

Things we need to consider when fetching the data are stated below. We also need to include related dimensions in the querying logic.

| Attribute                   | Localized                         |
|-----------------------------|-----------------------------------|
| name                        | yes                               |
| description                 | yes                               |
| data type                   | no                                |
| unit                        | yes                               |
| currency, currency exponent | no                                |
| time unit                   | no                                |
| dimension types             | no                                |
| scales                      | no                                |
| values                      | yes, several localized attributes |
| hierarchies                 | yes, several localized attributes |

Some of those are already contained in and fetched with the cube shape.

**User story**

I would like the `DataCubeComponents` query to be `CONSTRUCT`-based, instead of being `SELECT`-based.

**Definition of Done**

`DataCubeComponents` query (including its many sub-queries) is consolidated into smaller number of CONSTRUCT queries, which should result in improved performance of fetching dimension metadata. Wherever possible SPARQL queries (i.e. values and hiearchies) are fired concurrently.

**Comment by bprusinowski** [comment]
After investigation, it turned out using `DESCRIBE` along with `#pragma describe.strategy cbd` is more performant than asking for specific properties, probably due to some internal optimizations of cbd strategy.

As we then need to only fire one additional query for unit labels, it was decided that the current way of fetching components metadata is more performant than a complete switch to tailored CONSTRUCT queries.

Side note: this doesn't only impact component metadata, but also dimension values fetching, as we need to know upfront the data type of a dimension, along with several other things, to be able to fire a proper query (min / max or all dimension values with metadata). It means that if we switched to tailored CONSTRUCT queries, we would need to anyway fire one additional query just to get data type (which was taking a longer time than pure DESCRIBE on cube's shape) and only then fire a query for dimension values / and hierarchies.
