### ISSUE TITLE
Add a Filter doesn't work

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1402]
the "Add filter" function no longer works.

**To Reproduce**

1. Open https://int.visualize.admin.ch/fr/v/GQ9DY9LLi-vK
2. Copy and edit
3. Try to Add a (optional) filter.

**Expected behavior**

**Screenshots or video**
If applicable, add screenshots or a short video to help put your problem into a context.

**Environment (please complete the following information):**

- Visualize environment and version:INT v3.26.3 ([06fdd13]

**Additional context**

**Comment by bprusinowski** [comment]
Hi @sosiology, thanks for adding another example of a broken filter! However, this issue just looks very similar to the one reported in this issue, but in fact is different.

In the example you shared, the `Active Since` dimension misses a data type, which means that we can't properly filter the observations when checking for possible filters. It would be best to reach out to the maintainer of the cube to add a data type to this dimension 👀

**Comment by sosiology** [comment]
Tested on TEST, LGTM. Thanks @bprusinowski 
Can we deploy this fix to INT?

**Comment by bprusinowski** [comment]
@sosiology it should have been deployed already, but for some reason it wasn't, I started the pipeline to deploy to INT again, hope this will fix the problem 🤞
