### ISSUE TITLE
Drop-down list with double entries

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1418]
The items in the "Heavy Metal" list appear twice in following cube https://int.visualize.admin.ch/en/v/wKxC-xJfKevw.

Steps to reproduce :
1. Open: https://int.visualize.admin.ch/en/v/wKxC-xJfKevw
2. Show the "Heavy Metals" filter
3. Each item appears twice
4. Copy and edit the visualization
5. Edit Filter "Heavy Metal"
6. Each item appears twice

cube: https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd006601-bodenbelastung-durch-schwermetalle-r5zqggxxgl9/csv-mapping, which uses a Shared Dimension.

The following checks have already been performed:

- Shape is present
- The list of possible items in the dimension looks clean https://s.zazuko.com/NH4NYQ
- The history of the individual versions looks clean https://s.zazuko.com/3sG141V

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/ce8418e1-f097-4f27-84d0-b64354696e9d)

**Environment (please complete the following information):**

- Visualize environment and version: v3.27.1 [8c3e7f9]
- Browser and version [e.g. Chrome 107]

**Additional context**

**Comment by bprusinowski** [comment]
Hi @ortnever, thanks for reporting the issue – it looks like a problem with the data, or a situation we haven't anticipated in Visualize yet.

Basically, we expect a dimension value to have up to one `schema:identifier` parameter, as otherwise we wouldn't know which one we should show in the application. Currently, in the dataset from the issue, we have two identifiers applied to every value, which leads to the duplication we see in the filters (see slightly adjusted SPARQL query [here](https://s.zazuko.com/2WCUFDt)).

Is the double-identifier situation something expected? If so, we would need to think about how to handle such cases, also from the design side. If not, updating the data to only contain a single identifier would solve the situation.

Let me know what you think about this @ortnever 🙏 

cc @sosiology

**Comment by ortnever** [comment]
@bprusinowski, for the moment we're going to fix the Shared Dimension. We'll get back to you if this becomes a requirement for Visualize later on.
Thank you

**Comment by bprusinowski** [comment]
Thanks for the feedback @ortnever! Let's keep this in mind for the future 👍

**Comment by bprusinowski** [comment]
Please reopen the issue if the problem still appears after fixing the Shared Dimension 🙏

**Comment by Rdataflow** [comment]
@bprusinowski once you switch to a query spanning over multiple dimensons and you receive a result w/o list i.e. cube > dimension > element > properties this issue would be gone...

**Comment by ortnever** [comment]
Thanks for your input Thomas.
Does this mean that we don't necessarily need to solve the problem of 2 identifiers per element? 
I thought it would be cleaner to modify the SD and use the CAS number as identifier and put the abbreviation in schema:alternateName, as we've done for other SDs. However, I noticed that there wasn't always a CAS number for each element.

**Comment by bprusinowski** [comment]
@ortnever from my point of view it would be best to update the shared dimension, as the improvement @Rdataflow mentions would not be tackled before the PROD release 👀 

Generally, we could also solve this right now, but having more than one identifier isn't something we expect, and the problem is more the conceptual approach to such situations, and not the technical "fix" of selecting e.g. the first identifier in case there are multiple 👍

**Comment by Rdataflow** [comment]
@ortnever still prefer you go for 1 identifier.
A. You dont need to wait for a next release...
B. It is less duplicate information as the cemical element is in alternate Name still.
