### ISSUE TITLE
Dashboards Iteration 2: Layout / Grid Options

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1515]
**Description**
the goal of this iteration is to work on **layout options** for the dashboard features. It includes Design work such as defining how many charts are shown per row and UI enhancements needed for the feature. The development work includes validating the feasibility of the proposed design, and a **first implementation of an enhanced Dashboard Layout option** allowing the user to place multiple charts on a grid and order them as needed.

**DoD**
A user in visualize can create a dashboard with different charts on a single canvas, allowing them to order the charts beyond the existing options of Tall and Vertical layout

**Comment by KerstinFaye** [comment]
@ptbrowne I collected some feedback in our [shared document  ](https://www.notion.so/interactivethings/Sync-Kerstin-Patrick-7267a6e0e0e24218a5e0c4094f19833e?pvs=4)
- I tested the reordering of charts within the dashboard. I'm not sure about the fact that the charts are pushed down instead of the right.
- I also realized that when resizing the hight of charts some content is cut.

**Comment by ptbrowne** [comment]
I think for the height it has been solved by @bprusinowski in https://github.com/visualize-admin/visualization-tool/pull/1585. For the other one, it is a bit trickier, I think we can have another issue for this.

**Comment by ptbrowne** [comment]
I created https://github.com/visualize-admin/visualization-tool/issues/1588 to track the wrap behavior, this way we can move this issue to testing.

**Comment by sosiology** [comment]
Moving this issue to "Client Review" as i it was part of Sprint 5.9 and we are tackling enhancements in separate issues.
