### ISSUE TITLE
PROD : "This chart is not using a trusted data source" for a cube with Status "Published"

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1671]
Visualize PROD displays the message “This chart is not using a trusted data source” even though my cube has a “published” status.
https://www.visualize.admin.ch/en/v/fbh2uRXoahuQ

For the same cube (same Data Source = PROD) and the same Visualization, Visualize INT, does not display the message, which seems correct to me.
https://int.visualize.admin.ch/de/v/bleiyvYFAVUH

Is there a reason why this message is displayed or is it a bug?

**Environment (please complete the following information):**

- Visualize environment and version: PROD v4.0.0 ([3199e34]
- Browser and version : Edge

**Additional context** Add any other context about the problem here.

**Comment by sosiology** [comment]
@ortnever thank you for reporting the issue. The message is being shown on PROD to be due to the changes to the cached endpoint which is not yet on PROD. The application code checks to see if the endpoint is "trusted" and as we currently expect the non-cached version on PROD the error is displayed. Once we deploy to PROD the (error) message will be gone. 

Cc: @bprusinowski

**Comment by ortnever** [comment]
@sosiology : Thank you for your explanation.
