### ISSUE TITLE
Dataset selected, but the "next" button just erase that selection

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#168]
Today I wanted to see what the visualization tool does when the title of a cube is only given in french.
I saw that, no matter the user's choice about the interface language, this datataset was "correctly" displayed with the french title.
However, when pressing the "next" button, the tool just refreshed the page, stayed on the dataset selection but loosing my selection of the given dataset.

[edited]
I am not sure yet of why the dataset is not valid. Certainly a "stupid" mistake, but an error message would help for sure.

Could this be related to some meta-data languages missing ? I am doing some trials.

**Comment by FabianCretton** [comment]
Could the reason be "too few data" ? In that little trial, I only have 7 observations.

**Comment by ptbrowne** [comment]
It seems like a validation bug when we retrieve the observations. I see this error in the console

<img width="904" alt="image" src="https://user-images.githubusercontent.com/465582/139855868-ab7e8ff2-4e46-4f94-819f-6c9808592be7.png">

It seems like `123` is to be validated as a string and it fails because it's a number. In the data I see that it should be a xsd:integer so this seems weird:

```
<img width="396" alt="image" src="https://user-images.githubusercontent.com/465582/139856032-f18e73bd-cf08-4fe8-b45b-8cf1fff8ebd6.png">
```

I will look into it deeper... maybe @herrstucki has a clue ?

**Comment by herrstucki** [comment]
@ptbrowne I suspect that integers are used on a nominal/and or key dimension, and that the tool currently always expects these to be a string.

**Comment by herrstucki** [comment]
If you look at the metadata of the "No" and "Code-commune" dimensions, this is indeed the case: https://cube-viewer.zazuko.com/?endpointUrl=https%3A%2F%2Fint.lindas.admin.ch%2Fquery&user=&password=&sourceGraph=&cube=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_test_2021.10.27%2F10%2F
