### ISSUE TITLE
Locally saved charts

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#174]
Visualize admin does not provide a way to save or see last created charts. As far as I understand, it was done to avoid managing users/authentication/authorizatoin and the complexity that comes with it.
I wonder though if it would not be convenient to use local storage to save the user last created charts (so that we can have a small list somewhere in the menu) ? I think it could be helpful at least from a development point of view so that I do not create everytime the same charts. 

Crude UI would be:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/465582/139852863-53b6eed6-3621-400b-9117-9777ad0a16a4.png">

Do you think it could be useful ?

**Comment by herrstucki** [comment]
I think it would maybe even be useful to store drafts in the DB. Sometimes people share URLs like dev.visualize.admin.ch/create/abcd123 not realizing that only they themselves can see those. Maybe those could be pruned after 30 days or something.

To list all the local in-progress charts we would need to manage them in another localstorage item, since there's no way to list those otherwise.

**Comment by sosiology** [comment]
@ptbrowne can this issue/question be closed?

**Comment by ptbrowne** [comment]
No. We still do not have a way to do this and I think the distinction between local chart and published chart is still blurry, as users are still sometimes sharing URLs with local charts.

**Comment by sosiology** [comment]
Closing this issue as we have an open issue for the current WIP here https://github.com/visualize-admin/visualization-tool/issues/938
