### ISSUE TITLE
Cube cannot be processed in Visualize

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1791]
**Describe the bug** 
When trying to create a visualizations with the dataset [WASTA_Test](https://int.visualize.admin.ch/en/browse?dataSource=Int&dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2FBFE_OGD40_Wasserstatistik_test%2F4) the editor mode doesn't appear, but the user is taking back to the data set search page. 

**Steps to Reproduce**
1. Go to int.visualize.admin.ch
2. Search for the draft data set `WASTA_Test` dated 12.09.2024 (Draft data set so be sure to include drafts in the search!)
3. Select the data set and see the preview 
4. Click on "Start a visualization"
5. See that the page loads and then goes back to the dataset search page. 
6. See that no error message is shown.

**Expected behavior** 
After clicking on "Start a visualization" the user can start creating and editing a visualization with the data set. (e.g. is taken to the editor mode). If the editor mode cannot be initiated, the user receives some feedback to understand the behaviour. 

**Screenshots or video** 
 https://github.com/user-attachments/assets/63e2df44-c732-4aba-874f-c3d49d088cd0

**Environment (please complete the following information):**

- Visualize environment and version: [e.g. INT v4.9.2]
- Browser and version Chrome

**Additional context** Add any other context about the problem here.

- Link to the cube https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!bfeogd40wasserstatistik-glpyg6apey6/metadata. It is unclear if this is Visualize or an upstream issue -the cube has empty dimensions values. 
- This issue was reported by Silvan auf der Maur via Zulip: https://zulip.zazuko.com/#narrow/dm/113-Silvan-Auf-der-Maur-(BAR)

**Comment by sosiology** [comment]
Thanks for the input and hint @Rdataflow. This issue was initially reported by Silvan, so I will let him know.

**Comment by AdMSilvan** [comment]
> just guessing, maybe some mapping is broken - as dimsions are kind of mixed up and don't provide neither Literal nor IRI ...?

I had already ran it through cube validator and tried to fix some of the more glaring mistakes with the cube (such as missing data types) but I wasn't sure what was causing the lack of Literal or IRI for some values.
I thought it may be caused by the fact that in two columns there are empty values, but I was mainly curious about the behaviour of visualize and why it was not throwing an error when failing to load the cube. 
Do you think that is the most likely explanation? In that case I will forward that information to the user and encourage them to try with a different CSV to fix the error.

Thank you for your feedback!

**Comment by Rdataflow** [comment]
@AdMSilvan I guess the mapping of some shared dimension is still incomplete, you or the publisher may check and fix this 👍 
**International** isn't mapped yet 👁 
... or for an alternative quick fix they may simply drop those values which are not mapped 😉
