### ISSUE TITLE
The content is cut off in the last row of the table

### ISSUE THREAD

**Issue by BenjaminHofstetter** [visualize-admin/visualization-tool#1792]
The content is cut off in the last row of the table.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://visualize.admin.ch/de/v/_zFtZDl0kw12

The content is cut off in the last row of the table.

**Screenshot**
![Image](https://github.com/user-attachments/assets/07c069e6-2e64-4888-a31b-aa7a21f45ccc)

**Environment (please complete the following information):**

- Visualize environment and version: Prod
- Browser: Safari 18.0.1 (20619.1.26.31.7) and Chrome  130.0.6723.58

**Comment by cype** [comment]
What is the status of this issue? In my opinion, this is a pressing issue because users do not know that they are not seeing the full table and could come to misinterpretations.

**Comment by sosiology** [comment]
@cype thank you for your note. We are planning to investigate the issue this week.

**Comment by sosiology** [comment]
@BenjaminHofstetter @cype 
The fix is ready for your review on INT (int.visualize.admin.ch). Also see the example chart here: https://int.visualize.admin.ch/v/QGCXVC05n5uQ?dataSource=Prod  

We would appreciate if you could have a look and confirm that the fix works as expected. We are planning a deployment to Production with the fix next week.

**Comment by BenjaminHofstetter** [comment]
That looks great! Thanks a bunch!
