### ISSUE TITLE
Improve visibility of selected data set

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1800]
**Issue**
Users get lost in the visualization view after selecting a data set - as there was no reference to the data selected (in Editor Mode)

-    Idea: Use as the title for the data set
-    Idea: Add under “Zurück zu Vorschau"

**To consider**
- Users may not understand that the title can be changed / where it is coming from.
- With Dashboards it gets more complex.
 
Similar Feedback from Tobias: https://github.com/visualize-admin/visualization-tool/issues/1172

**Comment by noahonyejese** [comment]
@sosiology if I understand correctly it's about adding the title of the dataset under the "Back to review"  /  "Zurück zur Vorschau" and also as default Title of the Chart, like mentioned in #1172

In case this is the case I would not advise to put it bellow the "Back to preview"  /  "Zurück zur Vorschau" Button because there could be multiple Charts regardless the layout type.

**Comment by sosiology** [comment]
@noahonyejese this was part of the feedback we received from Christian. I think Kerstin is working on a design. Please align with @KerstinFaye before implementing a change

**Comment by noahonyejese** [comment]
> @noahonyejese this was part of the feedback we received from Christian. I think Kerstin is working on a design. Please align with @KerstinFaye before implementing a change
> 

Alright thanks

**Comment by KerstinFaye** [comment]
@noahonyejese I think we can as a first step bring the Datasourses section on top of the sidebar. Like this the Dataset will be more visible from the beginning on. In the same time I would like to make the +Add Dataset button a bit less dominant by having it as Button without outline if thats not too much effort? Also I would like to rename the section to Datasets instead of Datasources. 
@sosiology @bprusinowski

Figma Design Section: 
https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5843-47410&t=dHRj8k7zbWa368dB-4

**Comment by noahonyejese** [comment]
I will tackle this

**Comment by sosiology** [comment]
@KerstinFaye thanks for preparing this. I think it is a good solution to start with 💯 
Thanks for picking up the issue @noahonyejese

**Comment by sosiology** [comment]
Waiting for client feedback before proceeding with the solution.

**Comment by sosiology** [comment]
@noahonyejese @KerstinFaye @bprusinowski in the weekly call on 19.11.2024 the client approved the proposal to move the data sets to the top of the sidebar.
