### ISSUE TITLE
Time Filter doesn’t work correctly with intercative Filter

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#210]
https://test.visualize.admin.ch/en/v/Co7q6813SwiY
to reproduce :
- Select dataset "State accounts - Office"
- Next to Create a visualisation
- Select Chart Type "Areas”
- by Color : select "Operation" 
- by Filter Office : select Bundesarchiv 
- Button next
- Select Year by Interactive Filter (on the left side)
- Show Time Filter and change the settings (on the right side)

See also Home page Visualize, second example (Evolution of state account by office)
The selection changes when the language is changed.

**Comment by bprusinowski** [comment]
Fixed along with #220 – it turned out to be the same bug :)

**Comment by sosiology** [comment]
@bprusinowski thanks for checking. I just tested the timefilters and unfortunately it is still acting a bit buggy. When the timerange filter is activated the chart dissappears. 
Currently: 
- When i activate the time filters i don't see the chart
- When i activate the time range filter i dont see the same timeframe in the chart as shown in the right hand side bar. In the example below, i would expect the time range shown on the x-axis of the chart to show 21.05.2007 - 28.09.2020 analog the sidebar instead of 22.04.2015-22.04.2015
-  When i try to interact with the slider in the chart the slider jumps back to the initial position where the chart is not rendered (correctly)
- The issues persist when the chart is published. 
-  if i copy the published chart, and try to adjust the time filters it starts to flicker (not reproducable)

**Additional Information**
Tested on Desktop, in Chrome: Version 96.0.4664.55 (Official Build) (arm64)
Link to published Chart: https://test.visualize.admin.ch/en/v/l6cJmq9x7m49 

**Screenshots**
https://user-images.githubusercontent.com/29289679/143478626-b5ea4c47-8e7b-4970-97a6-3182577d4f65.mov
https://user-images.githubusercontent.com/29289679/143478661-771c1e08-dec2-4151-ae7b-df9edd7a3a0c.mov

**Comment by bprusinowski** [comment]
Hi @sosiology, thank you for double-checking - the fix is currently available on DEV and the broken TEST example should fix itself once we deploy to TEST

**Comment by sosiology** [comment]
@bprusinowski great. Thanks for the info - will check on dev 👍

**Comment by sosiology** [comment]
Dev LGTM -> thanks for the hint @bprusinowski

**Comment by bprusinowski** [comment]
Sure, np!
