### ISSUE TITLE
Browsing topic feedback

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#214]
The buttons "Browse categories" and "browse themes" lead to the same page. 
The "Themes" navigation should be displayed at the top of the left frame when "browse themes" is selected on the home page and vice versa. 
This is not a problem yet as there are few themes and categories in the lists, but it will become a problem as the lists get longer.
![image](https://user-images.githubusercontent.com/79834090/142829948-e9ca5af0-d304-452b-b5a5-b8a1465e1fd4.png)
![image](https://user-images.githubusercontent.com/79834090/142830042-db4b388b-c66e-43a0-bb2b-a9f7bc5fbd86.png)

**Comment by ptbrowne** [comment]
Thanks for the feedback @ortnever , we were planning to have full fledged "themes" and "organizations" pages but could not fit this into the sprint. The latest design from @AnninaWalker will actually show direct links to handpicked themes and organisations, on the homepage. This is not yet reflected on the implementation, but this will soon be the case.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/465582/142830608-1654c6a6-3165-4d8e-86a6-4dbb99565ce7.png">

**Comment by ptbrowne** [comment]
If you have any feedback on those homepage links, this is not yet implemented.

**Comment by ortnever** [comment]
I like the I like the new design proposed by Annina. The current page is far too long.  
I would add the sentence to inform that the data comes from LINDAS:
![image](https://user-images.githubusercontent.com/79834090/142999121-89a4eec5-fe5c-4eef-9a9f-484d863d80cb.png)
But I'm not sure it's a good option to show only the most common themes/organisations (it won't be clear to the user that there are other themes and/or organisations) and showing all of them would be too long once there are more datasets published. Another variant would be to put the two buttons "browse themes" and "browse organisations" instead of the lists?

**Comment by AnninaWalker** [comment]
Dear @ortnever Thanks a lot for your feedback. We would suggest the following then:

**Homepage**
On the Homepage, we show the search field as well as two buttons with "Browse Categories" or "Browse Organisations"
![2 8 1_l_datasets](https://user-images.githubusercontent.com/59613691/143045975-fd352677-1f2e-4c2f-94da-710bac636267.png)

If the user clicks on "Categories" the categories will be shown on top in the lefthand navigation. If the user clicks on "Organisations" the organisations will be shown on top in the lefthand navigation

**Lefthand Navigation**
Per default, only the 10 first entries **OR** the Top 10 entries are shown in the lefthand navigation. The user can click on "Show all" to reveal the full navigation tree
![2 8 3_l_datasets](https://user-images.githubusercontent.com/59613691/143046186-f9b6f4a5-39c9-424a-be91-f0d1f5f2e9b1.png)
.

**Lefthand Navigation Expanded**
With click on "collapse" the user can minimize the lefthand navigation again to the TOP 10 entries.
![2 8 4_l_datasets](https://user-images.githubusercontent.com/59613691/143046417-eaa5d980-7135-4be8-827d-1409f75913aa.png)

What do you think?

**Comment by ortnever** [comment]
Thank you Annina for your proposition. I have to discuss it with Markus W. and Sabine (in particular Home page). I give you Feed-back as soon as possible.

**Comment by ortnever** [comment]
Dear Annina, Markus Wüest and Sabine would like to keep the homepage, as it is currently on PROD

Small changes :
- remove the small symbols
- Reduce the space between "Create a visualization" and "Visualize data in just a few steps.."

The "Create a visualization" button leads directly from home page to the page according to your proposal.

Small changes :
- Replace the title "Swiss Open Government Data" (only usable for opendata.swiss) by "Select data to visualize" or something like that (feel free to adapt the text). 
- In the field "Search" write "Search Datasets".
![image](https://user-images.githubusercontent.com/79834090/143461853-fac9e302-3f28-4f0c-8b64-5783745e82a5.png)
![image](https://user-images.githubusercontent.com/79834090/143461998-6c3469db-9373-4cbc-b850-11785a4cb924.png)

**Comment by ptbrowne** [comment]
Thanks for your feedback Veronique ! I implemented most of the changes, and it will land soon on test.

- [x] Removed the browse themes/organiztions buttons from homepage, "create visualization" brings to browsing page
- [x] remove the small symbols
- [x] Reduce the space between "Create a visualization" and "Visualize data in just a few steps.."
- [x] In the field "Search" write "Search Datasets"

As for the the "Swiss Open Government Data" change on the browsing page, I am not sure how to proceed here, and I have questions.

- "Swiss Open Government Data" is already what we say on the homepage, and I do not see why this term is only usable for the opendata.swiss actually. I think that if we change it in the browsing page, we'd have to change it on the homepage too. Do you agree ?
- "Select data to visualize" would not work I think since this title is used for the whole page title, for example when you browse inside themes and organizations, it becomes the label of the category/organization. This is to reinforce the feeling that a theme/organization has its own page (maybe in the future with example viz per organizations, or more descriptions) that you can link to. IMHO "Select data to visualize" would be a bit out of place here.

@ortnever Can you explain to me why "Swiss Open Government data" is not really suitable here ? Do my points make sense ?
@AnninaWalker Maybe you have a suggestion here ?

**Comment by WTS21** [comment]
hello test

**Comment by ortnever** [comment]
@WTS21, @ptbrowne 
Thank you for your comments. I have discussed this delicate point with Markus Wüest. The official directory of Swiss open government data is opendata.swiss.  In Visualize we have only a small part of the data listed in the swiss open government data catalogue. Here is our proposal:
- Keep a fixed title for all pages with a list of datasets. 
This title would be "Search and select Data". The choice of category and organisation is visible in the left frame. It is not necessary to include it in the title.
on the home page you can leave "Visualize swiss open government data".

Another remark: 
In the left frame "Theme" should be replaced by "Categories" in English and "Temi" by "Categorie" in Italian (these are the translations used in opendata.swiss).

**Comment by AnninaWalker** [comment]
Dear Véronique @ortnever 

Thanks a lot for your feedback. I’ve been looking into your suggestion regarding to change the title to “Search and select Datasets” above the dataset list, and would like to propose you the following: 

As reflecting of what has been selected/filtered in the lefthand navigation in the title has been an integral part of the concept, we wouldn’t recommend to change the title overall. Showing what has been filtered in the title adds on one hand additional visual support to the user to understand immediately what datasets are represented in the list, and on the other hand allows us to scale the concept in the future to maybe even add more information. As we also work with unique Page ID's, it provides better orientation when sharing the URL. 

We’d therefore recommend to change the title to “All visualize.admin datasets” when entering the site without filtering, but to change the title as soon as something has been selected in the lefthand navigation.

What do you think? It would be great if you could provide us feedback until tuesday evening (30.11.21) so that we have enough time to implement the changes if necessary.

**Comment by ortnever** [comment]
Dear Annina,
Your proposition is ok for me, but wait please until tomorow. I have to discuss it intern. 
@WTS21, @PDumasBAR, @ZellerSabine do you agree with Annina's proposition? Thank you for your feed-back until tuesday evening (30.11.21).

**Comment by ortnever** [comment]
We have discussed this point with Markus and Sabine and they agree with your proposition. 

Another point was mentioned:
The orientation bar with the 4 steps (Dataset, Charttyp, Visualize, Annotate) is missing on the results page. If it can be added in the production version, it's nice, otherwise it will be for Sprint 3.2 (no hurry).
![image](https://user-images.githubusercontent.com/79834090/144027301-82196298-b9c7-4c77-a239-2814a7306816.png)
![image](https://user-images.githubusercontent.com/79834090/144027399-de29fd91-774f-4202-94af-515cd71b02eb.png)

**Comment by AnninaWalker** [comment]
Dear Véronique @ortnever 

We have intentionally removed the stepper on the "Browse by topics" page as we see this new "Dataset Page" more as an exploratory page where the user can browse and discover datasets and preview them before diving into the actual step-by-step process of creating a visualisation. 

Also now, that we have sort of "two different views" on the Dataset-Page (one with the list and one with the dataset preview), it didn't seem quite right to group this under one step.

Happy to discuss this tomorrow during our Weekly call.

**Comment by AnninaWalker** [comment]
@ptbrowne Together with BAFU we have agreed, that we won't add the Stepper on the Dataset-Page, but what we still have to implement is, that as soon as the user has clicked on "Create visualization" that we only show 3 steps. Step 1 = Chart type Step 2 = Visualize and Step 3 = Annotate. The first step "Dataset" needs to be removed


![Screenshot 2021-12-01 at 09 08 01](https://user-images.githubusercontent.com/59613691/144196298-58dc1b9c-50a7-4e83-b384-c84f4e7ece01.png)
.

**Comment by herrstucki** [comment]
How do people get back to the dataset selection then?

**Comment by ortnever** [comment]
Thanks for the question Jeremy. I mentioned this during the session. If step 1 is removed, there must be another possibility to return to the dataset preview. I think the current concept is very good and I will leave it like that at least for the Go-Live. We can always change it later if necessary.

**Comment by ptbrowne** [comment]
Thanks for all your feedback, your latest feedback @ortnever is treated in #245, I am closing this issue now that we have solved the issues, do not hesitate to open new issues if necessary.
