### ISSUE TITLE
Adjust link target for link "Created with visualize.admin.ch" below published chart

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#222]
The link "created with visualize.admin.ch" at the bottom of a published chart directs the user to the published version of the chart, should it not take the user to the visualize home page?

![Screenshot 2021-11-24 at 11 31 00](https://user-images.githubusercontent.com/29289679/143221855-358894a4-0771-4468-a52e-ea831bdc7348.png)

**Comment by ptbrowne** [comment]
Yes I think this would make more sense.

**Comment by ptbrowne** [comment]
This is very easy to change, @AnninaWalker was it intended ? From reading the code, it does not seem like a mistake.

**Comment by herrstucki** [comment]
IIRC, the intention was to link to the chart's page (considering the case where the chart is embedded in an iframe) and offer further actions on that page (copy, create new chart etc.). Otherwise there would be no way to get to the chart's page at the moment.

**Comment by ptbrowne** [comment]
Seems like maybe two links could be of use here. I think at least in an embed chart, the sparql link is less interesting than having a link to go to visualize.admin and a "remix this chart" link.

**Comment by AnninaWalker** [comment]
I would recommend to add two links then. This is basically what we do with the two buttons below the published chart, right, so it just would need to be reflected within the "card" when embedding a chart.

 I'd suggest to have links called:
 Erstellt mit visualize.admin.ch (-> link to homepage)
 Edit this chart (-> link to editor)
 
 Where does this SPARQL Link come from? Was this a request by the client?

**Comment by AnninaWalker** [comment]
As a sidenote: The buttons "Create new visualization" and "Copy this visualization" have caused great confusion during the User Testing. So I think if we have the links as above in the embeded chart, it is already a lot clearer, what to expect, when clicking on those links. In a next step, we can tackle the buttons as well ;-)

**Comment by herrstucki** [comment]
@AnninaWalker didn't we already change the wording on the buttons based on that user feedback?

I would _not_ link directly to the editor because I fear that dropping users directly there is a bit too much without additional context. I would argue to keep the link to the published chart page (like https://dev.visualize.admin.ch/v/swza7AHNDuiU), potentially only when the chart is embedded. If there's something to be optimized/fixed there, let's do that instead? Maybe all those additional links like the SPARQL download could then be shown there and we can clean up the embedded chart view?

Because generally, I wonder if adding more and more links is a good thing or if it just gets more confusing.

**Comment by herrstucki** [comment]
Also for reference, linking to the chart page instead of the home page is something that other tools like Datawrapper do. I think it's better to keep the current behavior because context is preserved, the content of the chart page is actually useful and it's easy to go to the home page from there, so the journey makes more sense. Again, if the chart page is lacking useful things or is confusing, let's fix the problem there.

**Comment by AnninaWalker** [comment]
@herrstucki No, at least on test the labels of the buttons still seem to be the old ones.

Regarding your other comment: I agree;-)

**Comment by ptbrowne** [comment]
I agree with cleaning the published view and having more links only in the chart view inside visualize.admin.
