### ISSUE TITLE
Maps: Color Palettes

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#284]
In general: What kind of Color Palettes are we using for the Continuous Color scales? Are they the ones from D3?
Cause the light colors seem extreeeemly light and therefore very hard to read, as the borders of the cantons are almost not visible.
<img width="1634" alt="Screenshot 2022-01-25 at 09 29 18" src="https://user-images.githubusercontent.com/59613691/150940513-f12e4e4c-919e-43a1-9b5d-8c6a14b98297.png">

**Comment by bprusinowski** [comment]
I think in this case it's due to a fact that most of cantons do not have any data attached, so all use the most light color possible - it shouldn't be as extreme in "normal" cases. But overall yes, these are D3 palettes. One thing I was considering was adding an ability to set a mesh color - would it make sense and solve this issue?

**Comment by AnninaWalker** [comment]
Not a 100& sure what you mean by mesh color?

**Comment by bprusinowski** [comment]
Ah, sorry - basically it's the border of the shapes :) Right now it's white / very close to white, but there also could be a color picker to choose the color there.

**Comment by AnninaWalker** [comment]
Ah cool, I like that idea. Maybe we could limit it to just a selection between either white or a dark grey for the borders? Not that people start creating purple borders ;-)

**Comment by AnninaWalker** [comment]
I assume it would affect all borders right? It would be an overall change and not only for one specific shape?

**Comment by bprusinowski** [comment]
Yes, exactly - it makes sense to limit this to a particular set of colors, I like the idea! I will then try to also implement this by the end of the sprint. Thanks!

**Comment by AFoletti** [comment]
Since we are talking color palettes, I allow myself to point out that since you are using a background map, the lighter colors of bluish palettes are very hard to see against the gray background. Sadly, I do not have a concrete proposal to solve the issue (and it may very well just be my personal perception)
