### ISSUE TITLE
Can't select values in optional filter

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#307]
To reproduce:
- go to TEST environment
- use a [Covid19 dataset](https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FCOVID19VaccPersons_v2%2F2%2F?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22covid%22%7D)
- select a bar chart
- add optional "Population" filter
- try to change its value

**Comment by ptbrowne** [comment]
My current understanding of why this happens:

Why the bug happens:

- We receive a min max for this dimension (understandably because we have too much unique values for this dimension) and thus, we do not try to fetch dimension values with the filters

Additional thoughts:
- The population dimension is understood as a nominal dimension
- I think it does not make sense to have this dimension as a filter
- This dimension is not marked as a measure on the cube creator
- If this dimension was marked as a measure, it would not appear in the optional filters dropdown

So I think the way to go forward with this would be to mark the dimension as a measure in the cube creator.

Any thoughts @AnninaWalker @l00mi ?

**Comment by l00mi** [comment]
I agree that this dimension is not giving any information (at least I understand) we should exclude it.
