### ISSUE TITLE
Year dimension issue on one of the example dataset

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#348]
When going on the homepage there is dimension error that is displayed.

<img width="596" alt="image" src="https://user-images.githubusercontent.com/465582/154030469-b9406304-1579-4821-bbed-717dc8d51132.png">

- [x] Check if this is something wrong in the data
- [x] Check if this is something that is problematic in production

**Comment by bprusinowski** [comment]
It seems that data provider changed a type of a time dimension, so the IRI is no longer "http://www.w3.org/2006/time#Year" but rather "http://www.w3.org/2006/time#year". This has been changed only on the INT environment of the Cube Creator (cube version no 9 & 10), that's why it still works on the production (cube version no 4).

I don't know whether a data provider wants to release a new version of the cube on the production (it would mean we should create a new chart example, but the new version of the cube should be released at the same time when we deploy to production, so both environments would be fixed) or the data provider should change back the dimension type to the old IRI (but if they decide to update the cube to e.g. version 9 on production, then it still would be broken).

Do you have any ideas on how to deal with that @ptbrowne? I think we should have stable examples on the homepage, maybe it would make sense to replace this example with a different one?

I am not sure if it's possible to update a certain version of the cube without creating a new version (I think it doesn't make a lot of sense), but this is what we would need in this case 😅

**Comment by ptbrowne** [comment]
Thanks for investigating @bprusinowski.

Short term solution: I think we should check with the responsible of the cube to see if he can publish the version with "year" on production and then we deploy. Do you know who is the responsible for the cube ?

Long term solution: I think you're right that it's not good that we are dependent on changing data here. I think it would be good to make a read-only copy of the datasets used on the homepage. Is it easy to make copy of cubes @l00mi ?

> I am not sure if it's possible to update a certain version of the cube without creating a new version (I think it doesn't make a lot of sense), but this is what we would need in this case 😅

I am not sure I have understood here what you meant, we fetch the latest version of the cube right ?

**Comment by l00mi** [comment]
Which cube are we speaking about?

**Comment by l00mi** [comment]
And it reminds me of a feature which was once discussed. That its possible to publish a graphic with a flag to keep the version of the cube, even if an update is published. Is this still somewhere on a radar?

**Comment by l00mi** [comment]
And it reminds me of a feature which was once discussed. That its possible to publish a graphic with a flag to keep the version of the cube, even if an update is published. Is this still somewhere on a radar?

**Comment by bprusinowski** [comment]
It's State accounts - Office (https://cube-viewer.zazuko.com/?endpointUrl=https%3A%2F%2Fint.lindas.admin.ch%2Fquery&user=&password=&sourceGraph=&cube=https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2FStateAccounts_Office%2F9%2F)

**Comment by bprusinowski** [comment]
@l00mi, I don't think we have it on our radar, at least this isn't something we plan to work on during this sprint. I am don't think we have it in our issues, maybe it would make sense to add it there @ptbrowne?

I think we also should be able to get a copy of needed inputs to create a fixed version of the example by using LINDAS querying service (there is an option to download the response). Do you think it makes sense to go this way @ptbrowne?

**Comment by ptbrowne** [comment]
We do not have this issue yet. Are there other usecases that you see @l00mi ? Otherwise I think just copying the dataset into an "homepage / readonly" dataset is simpler.

> I think we also should be able to get a copy of needed inputs to create a fixed version of the example by using LINDAS querying service (there is an option to download the response)

Mmh yes maybe but I have never created a cube yet, maybe that could be a good time for a first, but I'd prefer if there is an option to copy the cube easily that zazuko takes care of this if possible.

**Comment by l00mi** [comment]
There are other use-cases and it will pop up quite soon, I am sure. (I am surprised it got lost.) We have the use-case of I make a report which is fixed in time, and there graphic which gets added to websites to be up-to-date.

Anyhow the change in this dataset was rather unfortunate and should not happen again. (So as you like, but it was a fluke, and we can even change it back if you prefer for this. I will talk to @PDumasBAR on that one.

**Comment by l00mi** [comment]
We might improve it a bit here: https://test.visualize.admin.ch/docs#/charts/cube-update in saying that it is not allowed to change any properties.

Also I will add an issue that changes on the mappings are not possible once published.

**Comment by ptbrowne** [comment]
I think changing it in back in light of the incoming production release is a good move, thanks michael !

**Comment by PDumasBAR** [comment]
Tell me if you need me to do something here.

**Comment by bprusinowski** [comment]
Thanks @l00mi and @PDumasBAR – it turned out there was an issue in cube sorting by version on our side. It should be fixed once PR is reviewed and merged to a main branch.

**Comment by l00mi** [comment]
(-: I guess 1, 10, 2, 3 ?

**Comment by l00mi** [comment]
One question @bprusinowski was the literal ^xsd:integer ? If not that might be a good idea to add. Would this be breaking for you?

**Comment by l00mi** [comment]
Nothing urgent. I think the order was interpreted alphanumerically, which would have been correct actually if the version is "1"^^xsd:string.. And if its "1"^^xsd:integer the order should be interpreted numerically. So if currently we have no literal I will add ^^xsd:integer to clarify this in future. (And want to be sure that the current code will not fail then.)
