### ISSUE TITLE
map on lfi cubes leads to unexpected error

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#394]
**Describe the bug**
```
Unexpected error
An unexpected error occurred while displaying this chart.
```

**To Reproduce**
1. Go to https://test.visualize.admin.ch/v/B7w7ypOesqA9
2. See error

**Expected behavior**
show map

**Screenshots**
![image](https://user-images.githubusercontent.com/26090254/154974168-6a5f58d0-2356-408b-bca1-1df9612aaf29.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.4.1 ([aa247f1](https://github.com/visualize-admin/visualization-tool/commit/aa247f15ae11c81cadbced84d491bd6f8b106ef6))

**Additional context**
alternative steps to reproduce
1. https://test.visualize.admin.ch/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-20-None-None%2Fcube%2F1?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22lfi%22%7D
2. map
3. see error

**Comment by bprusinowski** [comment]
Hi @Rdataflow, it seems that no dataset with GeoShapesDimensions works with a map at the moment; it seems that `geo.ld.admin.ch/query` endpoint to retrieve shapes is down, so no coordinates are being fetched. I am checking with @l00mi if something changed on the backend side.

**Comment by Rdataflow** [comment]
@bprusinowski thx for this information on the reason. so let's wait for swisstopo to have it online again...

**Comment by l00mi** [comment]
@ludovicm67 Swisstopo is doing stresstest on geo.ld.admin.ch right now, correct? Btw. it is still not officialy in production.

**Comment by ludovicm67** [comment]
It's not in production and some various tests are currently being performed.
If it's used in productive workloads, it's at the risk of having some instability (that's the goal of a dev environment).

**Comment by FabianCretton** [comment]
I just saw that my maps were not working either.
Is there no way, and is it interesting or not, to have a more specific error for the user ?
I mean, If I am preparing a visualization, but the map display fails, as a user I will not know what is the problem. I would go back to the Cube Creator, check all my data, republish, etc...when the cause was Swisstopo end-point being down.
Could the message be "Geo data not available currently, please try again later" ? Or I don't know which appropriate message ?

**Comment by l00mi** [comment]
In general only error messages where the end-user can change something or react are shown. In the case of a failing endpoint, the end-user will not be interested because of which part it does not work. But we from the development, maintenance should get a message. @ptbrowne do you use already something like sentry.io or similar? We have sentry set-up for cube-creator.

**Comment by ptbrowne** [comment]
I think it's fair to add an error message, this way the user knows that when coming back later, this will surely fix their problem. We added one.

**Comment by ptbrowne** [comment]
No we haven't integrated sentry.io yet, it's a good idea.

**Comment by FabianCretton** [comment]
@l00mi i did describe what I think users would do if they want to show something on a map and just see a general error.
I think this is something to think about, or is it already the case that a user can now if there is a problem with its data or if this is an infrastructure problem ?

**Comment by FabianCretton** [comment]
I didn't see @ptbrowne answer here above, thanks for clarifying the situation for the end-user.

**Comment by FabianCretton** [comment]
@ptbrowne today I see the same problem.
Thank you for adding a tip in the error message.
However, the https://ld.geo.admin.ch/query end-point seems up and queryable at https://ld.geo.admin.ch/sparql/# 
If you query that end-point, does it mean it is up, but the data you look for are not available ?

**Comment by l00mi** [comment]
@FabianCretton we are using the soon to be productive geo.**ld**.admin.ch and not anymore the soon to be stopped ld.**geo**.admin.ch. Cheers.
