### ISSUE TITLE
Temporal Dimension not working

### ISSUE THREAD

**Issue by dabo505** [visualize-admin/visualization-tool#461]
**Describe the bug**
* I added `sh:datatype xsd:gYearMonth;`and 
`meta:dataKind [
        a time:GeneralDateTimeDescription;
        time:unitType time:unitMonth
      ]`
to the cube `arable-crops-mills/1`which gives an error in [visualize](https://test.visualize.admin.ch/browse/dataset/https%3A%2F%2Fagriculture.ld.admin.ch%2Ffoag%2Fagricultural-market-data%2Farable-crops-mills%2F1?previous=%7B%22type%22%3A%22organization%22%2C%22iri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-landwirtschaft-blw%22%2C%22includeDrafts%22%3Atrue%7D)
Is that because unit:Month and xsd:gYearMonth do not go together? 

 * I added `sh:datatype xsd:gYear;`and 
`meta:dataKind [
        a time:GeneralDateTimeDescription;
        time:unitType time:unitYear
      ]`
to the cube `arable-crops-collection-points/1`which does not give the same error, but the data doesn't load. 
Is this a related problem? 
https://test.visualize.admin.ch/create/d5NoePMKNXfl

**Comment by bprusinowski** [comment]
The first issue is due to the lack of accounting for `xsd:gYearMonth` time format on our side, I opened a PR for that. I am pretty sure the second issue is not related, as it seems only the dataset preview is not loading – it's possible to go further to a chart selection step, and then the data is loaded (I guess it's related to #457).

**Comment by dabo505** [comment]
Perfect, thanks. I just updated all cubes with gYearMonth and gYear and the initial error is gone now.
