### ISSUE TITLE
Year filter do not show all available years - problem in the data ?

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#498]
**Describe the bug**
Dataset "Öffentliche Ausgaben TEST 2" has observations from 1995 to 2020, every year.
When preparing a "table" visualisation, all years are visible, but when preparing a column graph for instance, the Filter only displays 1995 and 2020 (and not 1996, 1997....2019)

Here is a final visualization with the year filter: https://test.visualize.admin.ch/v/UNdsaAoMsc4o

How to find out where the problem is, is there a problem in the data ?
I made a first check, and did not find any error easily.

For information: the original cube has two measures: in % and In Mio. CHF (CHF) -> in the current published version, version 3, I did remove the "in %" measure, suspecting a decimal value to be wrong. But keeping only the "integer" value of "In Mio. Chf" did not help.

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.4.8 ([2a8c061]
 - Browser and version: Firefox 99.0

**Comment by AFoletti** [comment]
I have the exact same issue for the "Einmalvergütung für Photovoltaikanlagen" dataset

**Comment by bprusinowski** [comment]
Hi @FabianCretton and @AFoletti!

Thanks for raising this issue – I checked both mentioned cubes and they are missing a dataKind property on a Year dimension, which has to be set on a TemporalDimension in Step 3 in Cube Creator in order to be correctly interpreted by Visualize (just setting a data type of a year is not enough).

@ortnever this is also the case for Heavy Metal Soil Contamination dataset on PROD.

Please let me know if this solves the issue :)

**Comment by FabianCretton** [comment]
Thank you for your input @bprusinowski 
I can add the dataKind (I did already but did not publish yet). 
However, I do not understand what is happening, as, from my understanding, those values could be anything else then dates and could have no dataKind actually, no ?
So, why are there only two values present in the filter, this seems strange, no ?

**Comment by FabianCretton** [comment]
For information, the new cube publication, with the dataKind, is working and displays all the years: https://test.visualize.admin.ch/v/Ot9GV0D1_ONb

I am still interested for an answer about what was happening:
However, I do not understand what is happening, as, from my understanding, those values could be anything else then dates and could have no dataKind actually, no ?
So, why are there only two values present in the filter, this seems strange, no ?

**Comment by AFoletti** [comment]
I would have liked to test myself, but after the change I could not publish the data anymore, so I can't confirm.
I however have little doubt that hte fix you proposed would work. At the same time, I am interested in the answer to Fabian's question too

**Comment by ortnever** [comment]
For Heavy Metal Soil Contamination dataset, i did a test on Cube Creator int (same cube as in PROD)
If I define the dimension as "time dimension" I get following error. Probably because some observation have no data?
Search "Heavy Metal Soil Contamination" in https://test.visualize.admin.ch/  
![image](https://user-images.githubusercontent.com/79834090/168819232-a236b11c-263c-4ff0-8e57-bc6c1ba3ed11.png)

I don't know how to deal with this case.

**Comment by FabianCretton** [comment]
@bprusinowski , very interesting and happy that there is an explanation, thank you!
I have always wondered if we shouldn't have some more explanations that covers the relationship between the Cubes generated by Cube Creator and their use in Visualize, but I think that this page [1] contains now a lot of information
[1] https://test.visualize.admin.ch/docs/charts/rdf-to-visualize#possible-chart-types).

**Comment by ortnever** [comment]
@bprusinowski , I don't think that it can work because the attribute "Sampling period" hasn't a time Format in the csv. It's a string, i.e "1985-1989". But I tried to do what you said : For the dimension "Sampling period" I added "Time description" as Datakind, with Precison " year".

![image](https://user-images.githubusercontent.com/79834090/168988984-ffd9c0d1-d01b-40ed-8a2a-007295d1d697.png)

![image](https://user-images.githubusercontent.com/79834090/168989546-f2500dad-c9e8-455b-b222-0ca599d35e76.png)

but I get the same error message : 

![image](https://user-images.githubusercontent.com/79834090/168988686-75163598-6f81-46f5-a82b-5c5479106059.png)

**Comment by ortnever** [comment]
@bprusinowski : the problem was that I assigned "intervall" to the nominal Dimension "Sampling Period", and that I did'nt assign "Time description" as data Kind for the dimension "Sampling date". Thank you, Bartosz for your explanation above and thanks to @l00mi who helped me to discover my error.

**Comment by bprusinowski** [comment]
Great, I am glad it worked! I am closing this issue, and will reopen it if similar issues arise.
