### ISSUE TITLE
in PROD : No Data in Filter on the right side

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#499]
When selecting the x-axis or segmentation (colors), no data appears in the filter on the right. Only the number of entries that this dimension contains is shown.

1. Go to 'Visualise PROD"
2. Select a dataset
3. Select "Horizontal axis" or "Colors"
4. Filter on the right side is empty

**Expected behavior**
the values of the dimension should appear on the right frame so that the user can select them

**Screenshots**
![image](https://user-images.githubusercontent.com/79834090/162750622-cc974e4f-9c73-48eb-9822-1b7ee37ca826.png)

**Environment (please complete the following information):**
 - Visualize PROD v3.4.7 ([0d01260]
 - Edge 99.0.1150.55

**Comment by ptbrowne** [comment]
Are you still experiencing the problem @ortnever, there were hiccups lately due to a misconfigured firewall, but the issue has been solved. I can load the heavy metal dataset, select the X axis, and see filter values.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/465582/162768200-9083af84-4863-481d-bf71-37e4d82f0bcc.png">

**Comment by ortnever** [comment]
Thank you Patrick.
It's ok now !
Have a nice evening.
