### ISSUE TITLE
Switch visualization: Switch chart type via tab (1b)

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#515]
**Problem statement**
Currently an editor looses all the filter settings when changing to another chart type.

**Expected behaviour**

The editor should be able – while visualizing a chart – to switch to another visualization type anytime, while keeping the filter and configuration settings, and without having to go back one step to select another chart type.

**Concept**

Instead of having to choose a chart type first, the user will directly land on the editing page, after selecting a dataset. Per default, the chart type that makes the most sense for the selected dataset is shown (in this example, it is the bar chart).

See Design Mockups and Documentation [here](https://invis.io/9811YXLK6VU5#/464464049_presentation-Switch-Visualization-6-01)

Dependency: work can begin as soon as we receive approval of the "publish composition" designDerived from the following [issue](https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/299)

**Additional Context**
Derived from the following [issue](https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/299)
Issue on Gitlab: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/348

`+ button` not needed for this implementation as it is needed for the composition

**Comment by AnninaWalker** [comment]
@bprusinowski The Call to Action on top need to be slightly adapted into:
Select the desired Chart Type for your dataset and customize your visualization by using the Chart Options and Filters in the sidebar

**Comment by AnninaWalker** [comment]
Currently to close the popup I need to switch somewhere outside the popup. Not sure if the popup should close automatically after I have chosen a chart type. On the otherhand it's cool to quickly click through all the available charts. I'm torn about this one. Initially I would have said to automatically close the popup. Any opinions? @sosiology @bprusinowski @ptbrowne

**Comment by ptbrowne** [comment]
small remarks, I think it is really cool :)

1. border radius is not consistent between chart icons and popup
2. would be nice if the spinner did not make the rest of the popup jump
3. I think it would be better if the popup disappared after selecting something, since after selecting a chart you want to see the result

**Comment by AnninaWalker** [comment]
Yes, my initial thought was also to let the popup dissappear after selection. (See above) Let's do that.

**Comment by bprusinowski** [comment]
I agree, thanks for your inputs! I will introduce the changes :)

**Comment by AnninaWalker** [comment]
As Patrick has mentioned. Please also add a Border Radius to the Popup menu and a shadow, so that the Popup can be seen better. 
<img width="491" alt="Screenshot 2022-04-27 at 15 05 53" src="https://user-images.githubusercontent.com/59613691/165524699-cb0c29cb-fe40-4413-8d4e-792b552a9637.png">
<img width="1718" alt="Screenshot 2022-04-27 at 15 04 57" src="https://user-images.githubusercontent.com/59613691/165524842-3293b566-85b4-4213-9813-72eebb2b9e0f.png">

Mockup

<img width="1185" alt="Screenshot 2022-04-27 at 15 05 08" src="https://user-images.githubusercontent.com/59613691/165524884-fb99e6d5-9f76-4a9f-b0df-c0305f66eb7d.png">

**Comment by AnninaWalker** [comment]
I think that's all from my side! I love it 👍

**Comment by ptbrowne** [comment]
There is also the radius of the hover background of individual chart buttons that needs to be slightly reduced
