### ISSUE TITLE
Dataset without "eindeutige" Identifer Key (mouse over)

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#73]
For datasets where the identifier key isn't unique : When not using the colour distribution (Categories) the mouse over only shows the maximum value (https://test.visualize.admin.ch/en/v/YAhjezXrv__B), whereas a distribution + grouped columns shows each value (https://test.visualize.admin.ch/en/v/3XZDHhrGUHU1). We should always see all available values, in order to notice that the graph doesn't make sense. To be discussed if not appropriate.
![image](https://user-images.githubusercontent.com/79834090/116089720-69cf3780-a6a3-11eb-87a6-4449848d8da4.png)
![image](https://user-images.githubusercontent.com/79834090/116089748-718edc00-a6a3-11eb-9b1c-8c48262d1334.png)

**Comment by herrstucki** [comment]
I will have a look how this can be improved, although without supporting aggregation of values I'm not sure if this can be solved for simple chart types (areas, columns, lines).

So without aggregation, there should maybe be a way to detect these datasets and disable incompatible chart types?

Scatterplots can already deal with this, so could other chart types that can show distributions like [box plots](https://observablehq.com/@d3/box-plot), [range plots](https://observablehq.com/@chuckpr/range-plot), [dot plots](https://observablehq.com/@d3/dot-plot), [beeswarm plots ](https://observablehq.com/@d3/beeswarm)

**Comment by ortnever** [comment]
Ich verstehe dass solche Datensätze mit einfache Grafiktypen wie Säule, Pie usw. nicht dargestellt werden können (ohne Aggregation). Aber warum zeigt mir das Mouse-over im Bild A alle Werte und im Bild B nur das Maximum (40.5)?  Beide entsprechen die gleiche Auswahl, oder? Bill length für Jahr 2007, Arte «Adelie», und Insel «Biscoe» -> 5 Messungen. 
![image](https://user-images.githubusercontent.com/79834090/116197414-068de580-a735-11eb-8f4f-a57b804aa465.png)
![image](https://user-images.githubusercontent.com/79834090/116197495-21605a00-a735-11eb-8c16-131a7356f6a8.png)

**Comment by ortnever** [comment]
So without aggregation, there should maybe be a way to detect these datasets and disable incompatible chart types?
-> ja, es wäre gut. Wenn das Tool verhindern kann, dass solche Chart Typ  ausgewählt werden können, ist das Problem mit Mouse-over erledigt. Sonst müssen wir im Mouse over alle Werte sehen, um solche "sinnlose" Darstellung zu erkennen.

**Comment by herrstucki** [comment]
A short update on this issue: I tried looking into it and it appears to be more tricky than I thought. The current charts are built on the assumption that we're applying strict filters and that there is not more than one observation per x/y or x/y/color combination. Now, since filters become less strict by making non-Key Dimensions optional and since we have datasets that can even have multiple observations per unique Key Dimension combination, this assumption does not hold anymore.

I don't see a "quick" fix yet that would make the charts behave correctly. Unfortunately, I also don't have a practical solution yet for how to disable chart types that don't work (i.e. all excepct scatter plots and tables).

Technical note: Applying an implicit stack transform, i.e. stacking/summing up values, even when they're not differentiated by color, seems to be a correct solution for bar (and pie?) charts – although it doesn't make too much sense for some kinds of values. I'm not sure how line and area charts should behave since we cannot have more than one value per line/area series.

**Comment by herrstucki** [comment]
As discussed, for now the data publisher needs to ensure that there is only one observation per unique combination of Key Dimensions. Eventually, this will have to be validated on the cube creation side.

As this is something that is really not conciously supported, we can't just fix the tooltips but will have to revisit this conceptually. In the future, this tool might offer functionality to calculate aggregates on observations.
