### ISSUE TITLE
"Median electricity tariff per canton" cube cannot be selected

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#762]
**Describe the bug**
When selecting specific datasets, the error page "This page could not be found" is shown. 

**To Reproduce**
1. Go to 'https://visualize.admin.ch/'
2. Select data set "Median electricity tariff per canton"
4. See error. The same error also occurs when the data set "Median electricity tariff for Switzerland" is selected

**Expected behavior**
The data set should load, so the user can begin creating the visualization

**Screenshots**
<img width="944" alt="image" src="https://user-images.githubusercontent.com/29289679/194245289-8a70e49b-21a7-44fa-bdfd-a8a99bedd38d.png">

**Environment (please complete the following information):**
 - Visualize environment and version: [e.g. PROD v3.9.5 ([6063484](https://github.com/visualize-admin/visualization-tool/commit/60634847219602df66d80c0ad4045cb5d1673ff3))]
 - Browser and version [e.g. Chrome 95]

**Additional context**
The URL shows `CANNOT_FIND_CUBE`
https://visualize.admin.ch/en/%3FerrorId=CANNOT_FIND_CUBE&errorOptions=%7B%22iri%22%3A%22https%3A%2F%2Fenergy.ld.admin.ch%2Felcom%2Felectricityprice-canton%22%7D?dataSource=Prod

**Comment by ptbrowne** [comment]
It seems that on Lindas production, the cube has no "observationConstraint", see the [cube-checker](https://visualize.admin.ch/_cube-checker?cubeIri=https%3A%2F%2Fenergy.ld.admin.ch%2Felcom%2Felectricityprice-canton&dataSource=Prod). It has a shape on int but lacks several other attributes, see results of checks below.

@l00mi I think this is something to that you have to tackle on your side ? Tell me if I can do something.

---

## On Lindas production:

### Has a shape

Should have a shape through cube:observationConstraint
❌ No shape

### Has a creator

Should have a shape through dcterms:creator
❌ No creator

### Has a theme

Should have a shape through dcat:theme
❌ No theme

### Has a description

Should have a description through schema:description
❌ No description

### Is published

Should have a status (schema:creativeWorkStatus: [Published, Draft])
✅ Is published

### Is set to be viewable on visualize.admin

Should have a predicate schema:workExample <https://ld.admin.ch/application/visualize>
✅ Is viewable on visualize.admin.ch

## On Lindas integration

### Has a shape

Should have a shape through cube:observationConstraint
❌ No shape

### Has a creator

Should have a shape through dcterms:creator

❌ No creator

### Has a theme

Should have a shape through dcat:theme
❌ No theme

### Has a description

Should have a description through schema:description

❌ No description

### Is published

Should have a status (schema:creativeWorkStatus: [Published, Draft])
✅ Is published

### Is set to be viewable on visualize.admin

Should have a predicate schema:workExample <https://ld.admin.ch/application/visualize>
✅ Is viewable on visualize.admin.ch

**Comment by ortnever** [comment]
@ptbrowne I had a call with Michael this morning (he is in a confernce all the day, Maybe he cannot answer today...)
Michael explained to me that this is an option that needs to be changed in the queries. He told me that Zazuko had released a new version of a library. This version is available since yesterday and should fix this performance problem. Interactive should now use the latest version of this library. I do not know all the details.

The problem do not appear systematically. Sometimes the data load is just very slow and the data are finally displayed. Sometimes an error message is displayed "the page cannot be found".

cc : @l00mi thank you to complete my explanation

**Comment by ptbrowne** [comment]
There are two different issues:

- The performance problem, I opened a new issue here so that we do not mix the two together: https://github.com/visualize-admin/visualization-tool/issues/763
- The cube that cannot be found : here we have a problem with the data inside the cube (the problems that I described above), I think this is something that the publishers of the Electricity cube have to do.

I think the best here would be to hide the cubes from the search interface of visualize since they are not working correctly. In the cube creator, is it easy to remove the "workExample=visualize.admin" predicate ? This would ensure that those cubes do not appear in the search.

**Comment by ortnever** [comment]
Thank you Patrick.
I can't do anything on my side but I add Pierre to the discussion because he has a contact by Elcom.

@PDumasBAR : we were talking this morning about the problem with the dc/terms creator in Elcom datasets. Do you also want to ask Magdelena about the other attributes Patrick mentioned? Otherwise we're waiting for Michael to explain.

**Comment by magdasalatka** [comment]
@ptbrowne What is the SPARQL query you use to load the dataset?

**Comment by ptbrowne** [comment]
```
describe <https://energy.ld.admin.ch/elcom/electricityprice-canton>;
```

**Comment by ptbrowne** [comment]
Fixed with @magdasalatka republishing the cubes, thanks !
