### ISSUE TITLE
Range Filter also on the Left-Side Filters

### ISSUE THREAD

**Issue by l00mi** [visualize-admin/visualization-tool#79]
Year should also become a rangefilter on the left side of the filters section.

<img width="312" alt="Screenshot 2021-05-10 at 11 20 18" src="https://user-images.githubusercontent.com/502518/117637081-c4779180-b181-11eb-9aae-b9876e1fc95b.png">

**Comment by herrstucki** [comment]
I agree that this needs to be fixed. Instead of a range filter I would propose to only allow a single date to be selected however to be conceptually in line with the other dimension filters that are not mapped to a visual variable.

**Comment by mbch** [comment]
I discussed this topic with Vero and we came to the conclusion, that there are a lot of cubes, where we expect so many date values within a dimension, that a dropdown is simply not practicable.
What about the following approach:
Instead of one dropdown we have 3 (in case of Year-Month-Date, 6 for Y-M-D-H-M-S). At the beginning all dropdowns are empty. I move from left to right. Clicking the first dropdown shows all years that make sense (sense = where we have data available). I select a year, f.e. 2002. The next dropdown shows only the months within 2002 where we have data – so f.e 4 and 9. After selecting month 4 I get a dropdown of all days within 2002-04 that contain data. The idea is to keep the selection of values within the dropdown manageable, but guide the user to select only values that makes sense.

**Comment by herrstucki** [comment]
I would suggest a slider instead, similar to the range slider but only with one "knob".

**Comment by mbch** [comment]
A slider is also a good option - potentially in combination with Shift key to make the selection more granular? Is there a way to get a preview of a selected date? Having 5000 dates and trying to find the right one is very difficult.

**Comment by Rdataflow** [comment]
Brainstorming **how to choose a valid date**
![image](https://user-images.githubusercontent.com/26090254/118470310-dec3e900-b706-11eb-996c-e3e90d89158d.png)

**Comment by herrstucki** [comment]
Fixed by #83. The implemented approach is described there. Ideally the UI is smarter and only allows to input values that are _valid_ but this needs proper conception and design work beforehand.
