### ISSUE TITLE
Hierarchies in filter: limited to 4 levels ?

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#910]
**Describe the bug**
I have a hierarchy with 5 levels, but it seems only 4 levels are displayed in the filter.

NOTE: this is a project on TEST, and TEST is down at the moment of writing this issue.
But it should be back online soon...

The hierarchy in the Cube Creator, with the 5 levels defined:
https://test.cube-creator.lindas.admin.ch/app/hierarchies/dimension!!hierarchy!!hierarchy-swiss-foreign-trade-baskets+zolltarif-(on-bafu-helpers)

The link to visualize the project, once TEST is back on:
https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_foreign_trade_test_2%2F2?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22fab%22%7D&dataSource=Test

Example:
WK 1 -> WK 1.1 -> WK 1.1.C -> List of Zolltarifs 
The last node "List of Zolltarifs " should have children
Printscreen:

![image](https://user-images.githubusercontent.com/6167669/203749693-73656d84-d689-4652-98f7-49976c0d2627.png)

**Comment by ptbrowne** [comment]
Hey @FabianCretton, there is a limit to number of levels. I've increased it to 6 so that your usecase works. I hope we will be fine with this limit for the moment.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/465582/204335247-80564741-cfcd-4c31-8758-8415d55ee3f3.png">
