### ISSUE TITLE
Map zoom + and - buttons not working

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#932]
**Describe the bug**
I tried a map representation on this dataset:
https://int.visualize.admin.ch/en/create/Bi1ZypL-QY9F?dataSource=Int

and the + and - zoom buttons have no effect. The mouse wheel does work though

**Screenshots or video**
![image](https://user-images.githubusercontent.com/6167669/212649427-20bb52fe-5e83-4375-b2cf-585514f61256.png)

**Environment (please complete the following information):**
- Visualize environment and version: INT v3.18.0 ([91ae9f5]
- Browser and version: Firefox 108.0.2

**Comment by sosiology** [comment]
Additional Information: 
I tested the reported bug in the following browsers with the dataset ` fab_UBD010703_03 MFM-U Luftdaten Jahresmittel (Russ)`on INT and could not reproduce the error. 

- Chrome Version 108.0.5359.124 (Official Build) (arm64)
- Firefox Version 108.0.2 (64-bit)
- Firefox Version 108 on Windows via Browserstack

**Comment by FabianCretton** [comment]
Thank you for having a look.
On my Windows laptop, the +/- buttons do not react to a mouse click.
I tried with Firefox 108.0.2 (64 bit) and Edge  109.0.1518.52 
On another computer, Windows as Well, it DOES WORK with my firefox 107.0 (64-bit)

Let see if other people experience this...

**Comment by ptbrowne** [comment]
@FabianCretton This could be due to another transparent element stealing the click. Would be interesting if you have time to right click and do "Inspect Element". Then to screenshot the console tab of the inspector. This should hopefully tell us which element is "above".

**Comment by FabianCretton** [comment]
Here is the right-click/Inspect on the + button:
![image](https://user-images.githubusercontent.com/6167669/220057874-d382958d-1eeb-4b52-9f97-a9e4d49a3aa7.png)

But do you mean that you can not reproduce it ?

**Comment by ptbrowne** [comment]
Yes unfortunately I am not able to reproduce it.

**Comment by ptbrowne** [comment]
@rdataflow or @ortnever are you reproducing ?

**Comment by FabianCretton** [comment]
on my side, I still have this same issue. was my debug printscreen of any use ?

**Comment by ptbrowne** [comment]
I had a second look, and could find the reason. It is due to a setting that you have on your work machine that controls whether animations should be played (I guess that on government machines that are meant to be accessed remotely, animations are deactivated by default). The method we used to zoom in would use an animation and the framework would respect the setting of disabling animation, resulting in no animation, thus no zooming.
Now we say to the map to force the zoom since the animation is essential, and not cosmetic.

Thanks for the screenshot, it helped understand that the button was indeed working, but it was after that something was not working. It should be deployed promptly in int.
