### ISSUE TITLE
chart from dropped datacube is loading forever

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#967]
**Describe the bug**
chart from dropped datacube is loading forever

**To Reproduce**

1. Go to https://test.visualize.admin.ch/v/j1X16LsVYnnL?dataSource=Int

**Expected behavior**
A clear and concise error message is expected to happen.

- Visualize environment and version: [e.g. TEST v3.19.5]

**Comment by ptbrowne** [comment]
@Rdataflow I will look into it and make it so that we have an error message.

In the meantime, can you tell me what are exactly the semantics of "dropped cube" ? Does it mean it is completely deleted from stardog (1), or does it mean it is a soft delete (2) ? In case of (1), the best thing we can do is to show a 404, cube not found, whereas if dropping a cube is expected and done with a soft delete, we could put something more precise "cube is no longer available".
